image: atlassian/docker-release-maker:latest

pipelines:
  custom:
    new-releases:
      - parallel:
          - step:
              name: Bitbucket JDK 11
              services:
                - docker
              script:
                - git submodule update --init --recursive
                - export START_VERSION='6'
                - export END_VERSION='8'
                - export DEFAULT_RELEASE='false'
                - export DOCKER_REPO='atlassian/bitbucket-server'
                - export DOCKERFILE_BUILDARGS='BASE_IMAGE=adoptopenjdk:11-hotspot'
                - export DOCKERFILE_VERSION_ARG='BITBUCKET_VERSION'
                - export MAC_PRODUCT_KEY='bitbucket'
                - export TAG_SUFFIXES='jdk11,ubuntu-jdk11'
                - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
                - python /usr/src/app/run.py --create --create-eap
          - step:
              name: Bitbucket JDK 8
              services:
                - docker
              script:
                - git submodule update --init --recursive
                - export START_VERSION='6'
                - export END_VERSION='8'
                - export DEFAULT_RELEASE='true'
                - export DOCKER_REPO='atlassian/bitbucket-server'
                - export DOCKERFILE_VERSION_ARG='BITBUCKET_VERSION'
                - export MAC_PRODUCT_KEY='bitbucket'
                - export TAG_SUFFIXES='jdk8,ubuntu'
                - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
                - python /usr/src/app/run.py --create --create-eap
    jdk8-custom-release:
      - variables:
          - name: BITBUCKET_VERSION
          - name: DOCKER_TAG
      - step:
          services:
            - docker
          script:
            - git submodule update --init --recursive
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - >
              docker build -t atlassian/bitbucket-server:${DOCKER_TAG}
              --build-arg BITBUCKET_VERSION=${BITBUCKET_VERSION} .
            - docker push atlassian/bitbucket-server:${DOCKER_TAG}
    jdk11-custom-release:
      - variables:
          - name: BITBUCKET_VERSION
          - name: DOCKER_TAG
      - step:
          services:
            - docker
          script:
            - git submodule update --init --recursive
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - >
              docker build -t atlassian/bitbucket-server:${DOCKER_TAG}
              --build-arg BASE_IMAGE=adoptopenjdk:11-hotspot
              --build-arg BITBUCKET_VERSION=${BITBUCKET_VERSION} .
            - docker push atlassian/bitbucket-server:${DOCKER_TAG}
  branches:
    master:
      - parallel:
          - step:
              name: Bitbucket JDK 11
              services:
                - docker
              script:
                - git submodule update --init --recursive
                - export START_VERSION='6'
                - export END_VERSION='8'
                - export DEFAULT_RELEASE='false'
                - export DOCKER_REPO='atlassian/bitbucket-server'
                - export DOCKERFILE_BUILDARGS='BASE_IMAGE=adoptopenjdk:11-hotspot'
                - export DOCKERFILE_VERSION_ARG='BITBUCKET_VERSION'
                - export MAC_PRODUCT_KEY='bitbucket'
                - export TAG_SUFFIXES='jdk11,ubuntu-jdk11'
                - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
                - python /usr/src/app/run.py --update
          - step:
              name: Bitbucket JDK 8
              services:
                - docker
              script:
                - git submodule update --init --recursive
                - export START_VERSION='6'
                - export END_VERSION='8'
                - export DEFAULT_RELEASE='true'
                - export DOCKER_REPO='atlassian/bitbucket-server'
                - export DOCKERFILE_VERSION_ARG='BITBUCKET_VERSION'
                - export MAC_PRODUCT_KEY='bitbucket'
                - export TAG_SUFFIXES='jdk8,ubuntu'
                - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
                - python /usr/src/app/run.py --update
      - step:
          name: Update README
          image: python:3.7-alpine3.9
          script:
            - apk add --no-cache git
            - git submodule update --init --recursive
            - pip install -q requests
            - export DOCKER_REPO='atlassian/bitbucket-server'
            - python shared-components/image/push-readme.py
  pull-requests:
    '**':
      - step:
          image: python:3.7-alpine3.9
          services:
            - docker
          script:
            - apk add --no-cache git
            - git submodule update --init --recursive
            - pip install -q -r shared-components/tests/requirements.txt
            - export PYTHONPATH=./shared-components/tests:$PYTHONPATH
            - export DOCKERFILE='Dockerfile'
            - export DOCKERFILE_VERSION_ARG='BITBUCKET_VERSION'
            - export MAC_PRODUCT_KEY='bitbucket'
            - py.test tests/
            - py.test shared-components/tests/
            - export DOCKERFILE_BUILDARGS='BASE_IMAGE=adoptopenjdk:11-hotspot'
            - py.test tests/
            - py.test shared-components/tests/
definitions:
  services:
    docker:
      memory: 3072
options:
  size: 2x
